Done by following [this](https://www.youtube.com/watch?v=QUT1VHiLmmI) tutorial

In [1]:
import numpy as np

Initialise numpy array

In [14]:
a = np.array([1, 2, 3])
b = np.array([[9.2, 9.0], [5, 5.5]])

print("a.dtype =", a.dtype)
print("b.dtype =", b.dtype)
print("b.shape = ", b.shape)
print("b.ndim = ", b.ndim)

a.dtype = int32
b.dtype = float64
b.shape =  (2, 2)
b.ndim =  2


 c.itemsize =  2
d.itemsize =  4


In [19]:
c = np.array([1, 2, 3], dtype='int16')
d = np.array([1, 2, 3, 5, 5], dtype='int32')

print("c.itemsize = ", c.itemsize)
print("d.itemsize = ", d.itemsize)
print("b.nbytes =", b.nbytes )
print("d.nbytes =", d.nbytes )

c.itemsize =  2
d.itemsize =  4
b.nbytes = 32
d.nbytes = 20


Accessing elements

In [21]:
m = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 15]])
print(m)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 15]]


In [78]:
print("first row = ", m[0, :])
print("first column = ", m[:, 0])
print("elements > 5", m[m>5])
print("elements <= 5", m[~(m>5)])

first row =  [1 2 3 4 5 6 7]
first column =  [1 8]
elements > 5 [ 6  7  8  9 10 11 12 13 15]
elements <= 5 [1 2 3 4 5]


Initialise arrays

In [44]:
z = np.zeros((2, 4))
o = np.ones((2, 4))
oi = np.ones((2, 4), dtype='int32')
i = np.identity(3)

print("z = ", z)
print("\n o = ", o)
print("\n oi = ", oi)
print("\n i = ", i)

z =  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 o =  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 oi =  [[1 1 1 1]
 [1 1 1 1]]

 i =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
fives = np.full((4, 4), 5)

#see also np.full_like

print("fives = ", fives)

fives =  [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [45]:
rndm = np.random.rand(2, 2)
rndm_from_sample = np.random.random_sample(fives.shape)
rndm_int = np.random.randint(int('007'), size=fives.shape)

print("rndm = ", rndm)
print("\n\n rndm_from_sample = ", rndm_from_sample)
print("\n\n rndm_int = ", rndm_int)

rndm =  [[0.01868578 0.16351111]
 [0.00391742 0.42414664]]


 rndm_from_sample =  [[0.91569026 0.00613619 0.04396475 0.90237587]
 [0.74826412 0.8832449  0.10546059 0.45238119]
 [0.43434703 0.07704718 0.43853852 0.57524012]
 [0.15514041 0.93381308 0.52975904 0.5194616 ]]


 rndm_int =  [[1 1 0 2]
 [4 4 5 2]
 [3 1 4 5]
 [2 4 6 0]]


In [47]:
#Repeats

repeat = np.array([[1, 2, 3]])

r1 = np.repeat(repeat,3, axis=0)

print("r1 = ", r1)


r1 =  [[1 2 3]
 [1 2 3]
 [1 2 3]]


Math

In [66]:
mat = np.array([[1, 2, 3, 4, 1.57079633], [2, 3, 4, 55, 1]])

print("\n\nmat + 2 = \n", mat+2)
print("\n\nmat * 2 = \n", mat*2)
print("\n\nmat - 2 = \n", mat-2)
print("\n\nmat / 3 = \n", mat/3)
print("\n\nmat ^ 3 = \n", mat**3)
print("\n\nsin(mat) = \n", np.sin(mat))



mat + 2 = 
 [[ 3.          4.          5.          6.          3.57079633]
 [ 4.          5.          6.         57.          3.        ]]


mat * 2 = 
 [[  2.           4.           6.           8.           3.14159266]
 [  4.           6.           8.         110.           2.        ]]


mat - 2 = 
 [[-1.          0.          1.          2.         -0.42920367]
 [ 0.          1.          2.         53.         -1.        ]]


mat / 3 = 
 [[ 0.33333333  0.66666667  1.          1.33333333  0.52359878]
 [ 0.66666667  1.          1.33333333 18.33333333  0.33333333]]


mat ^ 3 = 
 [[1.00000000e+00 8.00000000e+00 2.70000000e+01 6.40000000e+01
  3.87578461e+00]
 [8.00000000e+00 2.70000000e+01 6.40000000e+01 1.66375000e+05
  1.00000000e+00]]


sin(mat) = 
 [[ 0.84147098  0.90929743  0.14112001 -0.7568025   1.        ]
 [ 0.90929743  0.14112001 -0.7568025  -0.99975517  0.84147098]]


In [67]:
#Algebra
mat2 = np.ones((5, 2))


print("mat*mat2 = ", np.matmul(mat, mat2) )
print("|i| = ",  np.linalg.det(i))

print("min(mat) =", np.min(mat), " \n", np.min(mat, axis=0) )
print("")


mat*mat2 =  [[11.57079633 11.57079633]
 [65.         65.        ]]
|i| =  1.0
min(mat) = 1.0  
 [1. 2. 3. 4. 1.]


Reorganizing

In [72]:
s1 = np.array([11, 22, 33, 44])
s2 = np.array([99, 88, 77, 66])

print("s1 reshaped => ", s1.reshape(2, 2))
print("s1 and s2 stacked => ", np.vstack([s1, s2]))
print("s1 and s2 stacked => ", np.hstack([s1, s2]))

s1 reshaped =>  [[11 22]
 [33 44]]
s1 and s2 stacked =>  [[11 22 33 44]
 [99 88 77 66]]
s1 and s2 stacked =>  [11 22 33 44 99 88 77 66]
